################################### Default Configuration ############################
baseurl = "https://www.epiclines.nz/"
title = "EpicLines"
theme = "vex-hugo"
# post excert
summarylength = "20"
# google analytics
googleAnalytics = "" # Ex: UA-123-45
languageCode = 'en-nz'
# disable language
disableLanguages = [] # disable language from here
timeZone = "Pacific/Auckland"

[pagination]
  pagerSize = 5

# unsafe html
[markup.goldmark.renderer]
unsafe = true

[permalinks]
  blog = "/blog/:year/:month/:day/:slug"

#################################### Plugins ##########################################

# CSS Plugins
[[params.plugins.css]]
link = "https://fonts.googleapis.com/css2?family=Montserrat:wght@400;700&display=swap"
#[[params.plugins.css]]
#link = "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css"
[[params.vendor.css]]
link = "vendor/bootstrap/bootstrap.min.css"
[[params.vendor.css]]
link = "vendor/themefisher-font/themefisher-font.min.css"
[[params.vendor.css]]
link = "vendor/slick/slick.min.css"

# JS Plugins
[[params.vendor.js]]
link = "vendor/jquery/jquery.js"
[[params.vendor.js]]
link = "vendor/bootstrap/bootstrap.min.js"
[[params.vendor.js]]
link = "vendor/slick/slick.min.js"


########################### Default parameters ##########################
[params]
logo = "images/logo.png"
logo_width = "100px"
logo_height = "30px"
# Meta data
description = "EpicLines"
author = "BinaryMist Limited"
copyright = '&copy; 2025 EpicLines - A division of BinaryMist Limited'
# currency
currency = "$"
# contact form action
contact_form_action = "https://formspree.io/f/xzzjwwaq"

surfURL = "https://www.epiclines.nz/surf/"
coreURL = "https://www.epiclines.nz/"
motorhomeURL = "https://www.epiclines.nz/motorhome/"

section = "core"


# Preloader
[params.preloader]
enable = true
preloader = "" # use .png , .svg or .gif format

# Subscription
[params.subscription]
# mailchimp subsciption
mailchimp_form_action = "https://gmail.us4.list-manage.com/subscribe/post?u=463ee871f45d2d93748e77cad&amp;id=a0a2c6d074" # replace this url with yours
mailchimp_form_name = "b_463ee871f45d2d93748e77cad_a0a2c6d074"                                                           # replace this code with yours

[taxonomies]
category = "categories"
tag = "tags"
vertical = "verticals"


######################## blog sidebar widgets #########################
[params.widgets]
sidebar = ["verticals", "categories", "tags"]

